### ISSUE TITLE
Color setting doesn't work

### ISSUE THREAD

**Issue by TheVoidSource** [Chris-Johnston/WifiLedClass#1]
Hi there, I've tried copying the samples and creating my own bulb.setColor's but they wont change the color of the light(s). It says it connects properly and I dont get any error logs but the colors only change to white when it first connects

**Comment by Chris-Johnston** [comment]
I would highly recommend you instead try @Danielhiversen 's https://github.com/Danielhiversen/flux_led library, as it is much more supported and maintained. I've only used this library for a single model of bulb, so it may not be fully compatible with others.
